@file:Suppress("WildcardImport")

package es.unizar.urlshortener.infrastructure.repositories

import jakarta.persistence.*
import java.time.OffsetDateTime

/**
 * Entity representing a click on a short URL.
 *
 * @property id Unique identifier for the click (autogenerated).
 * @property hash The hash of the short URL that was clicked.
 * @property created Timestamp when the click was registered.
 * @property ip IP address of the user who made the click.
 * @property referrer The referrer URL from where the click originated, if available.
 * @property browser The browser used for the click, if detected.
 * @property platform The platform from which the click was made, if detected.
 * @property country The country from which the click originated, if detected.
 */
@Entity
@Table(name = "click")
@Suppress("LongParameterList")
class ClickEntity(
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    val id: Long?,
    val hash: String,
    val created: OffsetDateTime,
    val ip: String?,
    val referrer: String?,
    val browser: String?,
    val platform: String?,
    val country: String?
)

/**
 * Entity representing a short URL.
 *
 * @property hash Unique hash identifier for the short URL.
 * @property target The original URL that is shortened.
 * @property sponsor An optional sponsor for the short URL.
 * @property created Timestamp when the short URL was created.
 * @property owner The owner of the short URL, if specified.
 * @property mode Mode or status of the short URL, represented as an integer.
 * @property safe Flag indicating whether the URL has been marked as safe.
 * @property ip IP address of the user who created the short URL.
 * @property country The country from which the short URL was created, if detected.
 * @property qr Optional QR code associated with the short URL.
 */
@Entity
@Table(name = "shorturl")
@Suppress("LongParameterList")
class ShortUrlEntity(
    @Id
    val hash: String,
    val target: String,
    val sponsor: String?,
    val created: OffsetDateTime,
    val owner: String?,
    val mode: Int,
    val safe: Boolean?,
    val ip: String?,
    val country: String?,
    @Lob
    val qr: ByteArray?
)
