# Spring Datasource
spring:
  datasource:
    url: jdbc:hsqldb:mem:.
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

springdoc.override-with-generic-response: false